### PR TITLE
Testing-events proposal

### PR DESCRIPTION
**Pull request by olensmar**
# Changes

Adds a "Testing Events" bucket with corresponding subjects and predicates.

see previous PR for discussions - https://github.com/cdevents/spec/pull/105

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has the [primer doc](https://github.com/cdevents/spec/blob/main/primer/_index.md) been updated if a design decision is involved
- [X] Have the [JSON schemas](https://github.com/tektoncd/community/blob/main/standards.md#tests) been updated if the specification changed
- [X] Has spec version and event versions been updated according to the [versioning policy](https://github.com/cdevents/spec/blob/main/primer/_index.md#versioning)
- [X] Meets the [CDEvents contributor standards](https://github.com/cdevents/.github/blob/main/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by olensmar** [comment]
@afrittoli @e-backmark-ericsson I recreated the PR with a single signed commit - hopefully that was the last hurdle..

**Comment by afrittoli** [comment]
Original PR: https://github.com/cdevents/spec/pull/105

**Comment by afrittoli** [comment]
Thanks @olensmar - I made a git diff of the two branches and it looks good, only a minor change:

```bash
➜ git diff pr_105 pr_126
diff --git a/spec.md b/spec.md
index 6440086..5969c7d 100644
--- a/spec.md
+++ b/spec.md
@@ -516,4 +516,4 @@ platforms.
 [typesystem]: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#type-system
 [datacontenttype]: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#datacontenttype
 [rfc2406]: https://tools.ietf.org/html/rfc2046
-[purl-spec]: https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst
+[purl-spec]: https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst
\ No newline at end of file
```

**Review by afrittoli — APPROVED** [review]
Thank you for your work on this!

**Comment by afrittoli** [comment]
@e-backmark-ericsson @xibz merging this PR as it was already approved in #105

**Comment by olensmar** [comment]
thank you @afrittoli - looking forward to implementing these events!

**Pull request merged**
