### PR TITLE
fix: `$id` of schema `testsuiterunfinished`

### LINKED ISSUE #186: fix `$id` of schema `testsuiterunfinished`
The `run` is missing in $id of `schemas/testsuiterunfinished.json`

```
"$id": "https://cdevents.dev/0.4.0-draft/schema/test-suite-finished-event",
```

### PR DESCRIPTION
**Pull request by davidB**
# Changes

align `$id` of schema `testsuiterunfinished` with subject value

FIX #186

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has the [primer doc](https://github.com/cdevents/cdevents.dev/blob/main/content/en/docs/primer/_index.md) been updated if a design decision is involved
- [x] Have the [JSON schemas](https://github.com/cdevents/spec/tree/main/schemas) been updated if the specification changed
- [x] Has spec version and event versions been updated according to the [versioning policy](https://cdevents.dev/docs/primer/#versioning)
- [x] Meets the [CDEvents contributor standards](https://github.com/cdevents/.github/blob/main/docs/CONTRIBUTING.md)

### CODE REVIEW

**Review by afrittoli — APPROVED** [review]
Thank you! Looks good to me.

**Review by e-backmark-ericsson — APPROVED** [review]

**Review by afrittoli — APPROVED** [review]
Thanks for the fix!

**Review by xibz — APPROVED** [review]

**Comment by afrittoli** [comment]
@davidB I just realised that your commit is not signed. Could you fix that please so we can merge this PR?

**Comment by davidB** [comment]
@afrittoli, Sorry I guessed sign-off was enough

**Pull request merged**
